### ISSUE TITLE
Elpi files cannot end with a comment

### ISSUE THREAD

**Issue by cloudyhug** [LPCIC/elpi#108]
Hello. The Elpi parser seems not to like files ending with a comment. Accumulating such files results in Coq failing and printing an empty error message. Not sure this is a real bug, it might be a design choice. However the error message could tell the user about it.

A minimal example can be obtained by making a `test.elpi` file containing only this line:
```prolog
% comment
```
and trying to accumulate it in Coq:
```coq
From elpi Require Import elpi.
Elpi Tactic mytactic.
Elpi Accumulate File "test.elpi".
```
VSCoq does not want to execute line 3 but does not print anything, and `coqc` shows the following empty error:
```
coqc Test.v
File "./test.elpi", line 1, characters 0-0:
Error: 
```
Again, I am not sure if this is a bug, but I would expect a file containing only comments to be imported normally, the accumulation just not having any effect.

**Comment by gares** [comment]
This is not Coq specific.
I seems a file with ends with a "%....\n" is fine, while "%...." is not.
