### ISSUE TITLE
Delaying constraints on multiple variables of different types

### ISSUE THREAD

**Issue by mb64** [LPCIC/elpi#120]
I wrote the code `declare_constraint (maybe-inst X Y K) [Y, K]` to run the predicate `maybe-inst X Y K` as soon as either `Y` or `K` become non-ground.

However, since `Y` and `K` are variables of different types, the typechecker issues a type error, and I have to pass the `-no-tc` argument to make it run.  Unfortunately, this means I miss out on the helpful feedback that the typechecker normally provides.

Is there a way to have the constraint trigger on either `Y` or `K` becoming non-ground, but also still get feedback from the typechecker about other, actual type errors in my code?

**Comment by gares** [comment]
Hum, I think I can make it variadic and support your usecase. Ill try later today.
