### ISSUE TITLE
Drop camlp5 extensible grammar

### ISSUE THREAD

**Issue by gares** [LPCIC/elpi#13]
I think we should write the parser using standard technology, say menhir.
Then define and document a handful of infix operators, taken from the examples we found online.
Eventually support families of infixes, eg `&&`, `&!&`, `&^&`, `&...&` with the same precedence of `&&`.

Remove `infix` and co.

**Comment by XVilka** [comment]
Yes, today is even more important, because recently both camlp4 and camlp5 appear even more dead than ever before: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/5

**Comment by XVilka** [comment]
And the official Camlp4 deprecation announcement: https://discuss.ocaml.org/t/the-end-of-camlp4/4216

**Comment by Blaisorblade** [comment]
Done by https://github.com/LPCIC/coq-elpi/pull/350 ?

**Comment by gares** [comment]
yes thanks
