### ISSUE TITLE
Failing clause head unification

### ISSUE THREAD

**Issue by mb64** [LPCIC/elpi#136]
In the following code:
```prolog
kind foo type.

type a ((int -> foo) -> foo) -> foo.
type b foo -> foo.

type p (foo -> foo) -> foo -> prop.
type q (foo -> foo) -> foo -> prop.

p K (a f\ K (f 0)).
q K R :- R = (a f\ K (f 0)).
```

`q` behaves correctly. But the clause for `p` fails to match sometimes when it should.
 - The query `pi y\ p b (F y)` succeeds.
 - The query `pi x y\ p b (F y)` fails.
 - The query `pi y\ q b (F y)` succeeds.
 - The query `pi x y\ q b (F y)` succeeds.

**Comment by gares** [comment]
Thanks again, this seems an instance of #135
