### ISSUE TITLE
findlib support (>= 1.13.8) + dune 2.9.3 cache = fail

### ISSUE THREAD

**Issue by Blaisorblade** [LPCIC/elpi#138]
I get this error if I build with dune caching enabled:
```
$ make build
dune build  @all
# hack: link camlp5.gramlib in the plugin
ocamlfind opt -shared -linkall -o _build/install/default/lib/elpi/elpi.cmxs \
	/Users/pgiarrusso1/.opam/4.13.1+flambda-coq813-bump-tmp/lib/camlp5/gramlib.cmxa \
	_build/install/default/lib/elpi/elpi.cmxa
ld: can't write output file: _build/install/default/lib/elpi/elpi.cmxs for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
make: *** [Makefile:33: build] Error 2
```

I thought about caching because of https://github.com/coq/coq/issues/15608.

## Known workaround

Disable dune cache in `~/.config/dune/config`.

**Comment by gares** [comment]
Oh, I see... I really don't know how to fix it now, but that `#hack` line will become useless soonish (https://github.com/LPCIC/elpi/tree/adt/parser)

**Comment by Blaisorblade** [comment]
Open issues, esp. with workaround, will have to count as docs :-).

**Comment by gares** [comment]
One "fix" would be to add a `plugin` line to the META file of `camlp5`, I've no clue why it is missing (together with its .cmxs). Dunno if it is fixed in camlp5 8.x

But since I want to ditch that dependency, I did the quick hack here in my garden. And I can't imagine a dune cache compatible hack here.

**Comment by gares** [comment]
This line disappeared in 1.15.0
