### ISSUE TITLE
Elpi 1.15.0 fails with unhandled exception  `Failure("lexing: empty token")` on the `&` conjunction operator. 

### ISSUE THREAD

**Issue by shonfeder** [LPCIC/elpi#142]
Here's a minimal reproduction: 

```
# pinned to master
$ elpi --version
1.15.0-2-gf5186ec
$ elpi
goal> true & true.
Fatal error: exception Failure("lexing: empty token")
```

I haven't dug into the updated docs enough yet to figure out if support for the `&` conjunction operator was meant to have been removed (I hope not!), but I expect we don't want this unfriendly parse failure regardless. :)

**Comment by gares** [comment]
I agree the new lexer should give a nicer error.

The new parser has &&, as a token family you can use. I kept single & out to be used as a synonym of , and maybe also in the head, but forgot to implement it I guess.

See the changelog. Use -legacy-parser while you wait for a fix.

**Comment by gares** [comment]
Nope, I broke it also in the legacy parser, since it shares some code with the new one.

**Comment by shonfeder** [comment]
Wonderful. Thank you! :)
