### ISSUE TITLE
Bug (in pattern matching?)

### ISSUE THREAD

**Issue by sacerdot** [LPCIC/elpi#19]
The test in

[B.txt](https://github.com/LPCIC/elpi/files/1956684/B.txt)

does not pass. Expected behaviour: it should pass and it should pass by expanding the O = t and OUT = t as well. I suspect a bug in unification.

**Comment by gares** [comment]
```prolog
translate T T' :- transl (lambda singleton _ \ T) T'.
transl (lambda Gamma _ \ star) (lambda Gamma _ \ star).
transl (lambda Gamma gamma \ lambda (A gamma) x\ M gamma x) OUT :-
 (pi w \ locDecl w (setSigma Gamma A) => (p1 w (P1 w), p2 w (P2 w))),
 (transl (lambda (setSigma Gamma A) gamma_x \ M (P1 gamma_x) (P2 gamma_x)) O),
 (O = (lambda (setSigma Gamma A) gamma_x \ M' gamma_x)),
 OUT = (lambda Gamma gamma \ lambda (A gamma) x \ M' (pair Gamma A gamma x)).
transl (lambda Gamma gamma \ p (X gamma) (Y gamma)) OUT :-
 OUT = (lambda Gamma gamma \ p (X gamma) (Y gamma)).

test A :-
 translate (lambda singleton x \ lambda singleton y \ p x y) A.
```

**Comment by gares** [comment]
I think the test file is incomplete (eg there is not constant `t` so the expected result cannot be right).
The trace looks OK to me, so I can't debug this bug report as it is.

**Comment by sacerdot** [comment]
True, the file I submitted is not self-contained. I will try to make a simpler self contained one.
Tracing the problem a bit, it seems to be an unification bug. Compare the two following problems.
They only differ by equivalent representations of the same term. The first one fails, the second one succeeds:

unif 113 {{{ ^0:elim_setSigma (.<x0 \ .<elim_setSigma x0 (x1 \ setSigma singleton (x2 \ singleton)) (x1 \ x2 \ x1)>_1>_0 x0) (x1 \ singleton) (x1 \ x2 \ x2) =1= ^0:.X1^1

vs

unif 12 {{{ ^0:elim_setSigma (elim_setSigma x0 (x1 \ setSigma singleton (x2 \ singleton)) (x1 \ x2 \ x1)) (x1 \ singleton) (x1 \ x2 \ x2) =1= ^0:.X1^1

**Comment by sacerdot** [comment]
This time the file should be self-contained.

The two unification problems in my previous message are triggered by
testbbb B 
and
testccc C

[bug.txt](https://github.com/LPCIC/elpi/files/1992978/bug.txt)
