### ISSUE TITLE
Opam release

### ISSUE THREAD

**Issue by pitag-ha** [LPCIC/elpi#190]
From what I can see, the [latest `elpi` opam release is 1.9.1](https://github.com/ocaml/opam-repository/blob/master/packages/elpi/elpi.1.9.1/opam), whereas the latest GitHub release is 1.17.0. Is that right? If so, would it be possible to submit the last GitHub release to Opam? The reason why that would be nice for us is to have a version on Opam that doesn't depend on `ocaml-migrate-parsetree`.

**Comment by gares** [comment]
Hum, all releases are there, see for example:
https://github.com/ocaml/opam-repository/blob/master/packages/elpi/elpi.1.17.0/opam

**Comment by pitag-ha** [comment]
My mistake, I went too quickly through a list, missing the details. Thank you!
