### ISSUE TITLE
[doc issue?] ELPI fails to unify functional constants up to eta-espansion

### ISSUE THREAD

**Issue by sacerdot** [LPCIC/elpi#22]
goal> (pi F \ simpl (x \ F x) F) => simpl (x \ a x) a.
goal> a = x \ a x.

both fail, but
1) they should succeed when a has function type
2) fail otherwise

The implementation of ELPI is untyped, thus ELPI does not work up to eta.
This should be documented and compared to the behaviour of Teyjus, if they differ.

**Comment by ThatDaleMiller** [comment]
Teyjus does the eta conversion correctly.   For example, using the built-in constant size, we have

```
[toplevel] ?- size = (x\ size x).

yes

[toplevel] ?- 
```
A fix to this in ELPI could be to use eta-expansion at certain few points in unification: probably only when a disagreement pair is between a lambda-abstraction and a non-lambda-abstraction (or between lambda-abstractions of different length).  In that case, use eta-expansion to increase the shorter binder to the same length as the longer binder).

**Comment by gares** [comment]
> A fix to this in ELPI could be to use eta-expansion at certain few points in unification: probably only when a disagreement pair is between a lambda-abstraction and a non-lambda-abstraction (or between lambda-abstractions of different length). In that case, use eta-expansion to increase the shorter binder to the same length as the longer binder).

I agree. This is the same technique used to implement eta in Coq. It is done on demand during conversion (that is untyped).
