### ISSUE TITLE
`name` make typechecking wrong

### ISSUE THREAD

**Issue by FissoreD** [LPCIC/elpi#222]
A premise like `name X` seems to create some typing issues.

Example which should not typecheck:

```prolog
type p1 A -> list A -> o.

type p2 list A -> A -> o.
p2 ACC X :- name X, p1 ACC X. % Here the typing error
```

Without `name` the typechecker raises the good error:

```prolog
type p1 A -> list A -> o.

type p2 list A -> A -> o.
p2 ACC X :- p1 ACC X.
```

**ERROR :** `File ..., line 4, column 0, character 53: Error: X has type X26 but is used with type (list (list X26))`

**Comment by gares** [comment]
yup, the type checker is wrong here. name expects `any`, and `X` has a variable type, the type checker fixes it to any, making it escape the next check.
