### ISSUE TITLE
Unification in the head of a rule and move of binders

### ISSUE THREAD

**Issue by FissoreD** [LPCIC/elpi#256]
```prolog
pred u o:(int -> int).
u (y\y).

pred main.
main :-
  pi x\ u (y\ X x y), print "The result X" (X x).
```

In the code above, the code should unify `(y\ X x y)` with `(y\y)`.
However, the result printed by `print "The result X" (X x)` is `y\x`.

I've inspected the trace and see that at a certain moment, the interpreter does the following unification:
```
^1:c1 \ .X0 c0 c1 =0= ^0:c0 \ c0
then: 
^1:.X0 c0 c1 =1= ^0:c0 
then:
move c0 from 0 to 1
then:
^1:.X0 c0 c1 =1= ^1:c0 
```
this last unification succeeds and assigns `x\y\x` to `X0`

I think the term to be unified should be `^1: X0 yc0 c1 =0= ^1:c1` (the right-hand side is c1 and not c0), but don't know 
where to change the code...

As a small remark, note that the very similar program below behaves as I expect:
```prolog
pred main.
main :-
  pi x\ (y\ X x y) = (y\y), print "The result X" (X x).
```

**Comment by FissoreD** [comment]
Maybe this script is more similar to the one using the `u` predicate:
```prolog
pred main.
main :-
  Z = (y\y),
  pi x\ (y\ X x y) = Z, print "The result X" (X).
```

**Comment by gares** [comment]
@FissoreD please have a look at #259
