### ISSUE TITLE
pre built binaries

### ISSUE THREAD

**Issue by hyperswine** [LPCIC/elpi#258]
Im having some trouble building elpi on my machine (M1 mac mini), says zstd 1.5.5 not in PATH even though Ive installed zstd 1.5.6, so not sure whats going on. If possible, could pre built binaries for the common arches like linux and macos be included in the release?

**Comment by hyperswine** [comment]
I downgraded to ocaml 4.13.1 and it worked, so it seems to be a problem with that

**Comment by gares** [comment]
CI builds the binaries, you can find them here for example: https://github.com/LPCIC/elpi/actions/runs/10164440173
