### ISSUE TITLE
elpi returns a unifier strictly worse than the MGU.

### ISSUE THREAD

**Issue by KiJeong-Lim** [LPCIC/elpi#296]
The environment was [https://lpcic.github.io/coq-elpi-www/tutorial-elpi_lang.html](https://lpcic.github.io/coq-elpi-www/tutorial-elpi_lang.html)
The coq-elpi code was:
```coq
From elpi Require Import elpi.
Elpi Command tutorial.
Elpi Accumulate "
  kind i type.
  type f (i -> i -> i).
".
Elpi Query "pi c\ pi d\ X c = f (Y c d) (Z c c).".
```
Elpi returns:
```
X = c0 \
f X0 (X1 c0 c0)
Y = c0 \ c1 \
X0
Z = X1
```
However, the MGU is $\{ X := \lambda c. f (H_1 c) (H_2 c c), Y := \lambda c. \lambda d. H_1 c, Z := H_2 \}$.
Is this a bug?

**Comment by gares** [comment]
Looks like a bug

**Comment by KiJeong-Lim** [comment]
elpi works right. I tested it. Only https://lpcic.github.io/coq-elpi-www/tutorial-elpi_lang.html has a problem.

**Comment by gares** [comment]
Sorry, I did not look at the URL with attention. That html file is super outdated, it says Coq 8.9. Do I still link that somewhere? This is the current tutorial: https://lpcic.github.io/coq-elpi/tutorial_elpi_lang.html

**Comment by KiJeong-Lim** [comment]
I had not known how to execute elpi. The reason why I tried coq-elpi (and had implemented my lambda-Prolog interpreter in Haskell) was that I did not know how to execute elpi. But, I found about it today. Everything is now okay!
