### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by krpcannon** [LPCIC/elpi#5]
Getting this report after running make:

`Makefile:128: .depends: No such file or directory
Makefile:128: .depends.parser: No such file or directory
OCAMLDEP .depends.parser            
OCAMLDEP .depends                   
OCAMLOPT elpi_util.cmi              -c
OCAMLOPT elpi_util.cmx              -c
OCAMLOPT elpi_ast.cmi               -c
OCAMLOPT elpi_ast.cmx               -c
OCAMLOPT elpi_trace.cmi             -c
OCAMLOPT elpi_trace.cmx             -c
OCAMLOPT elpi_parser.cmi            -c
OCAMLOPT elpi_parser.cmx            -c -pp camlp5o
OCAMLOPT elpi_ptmap.cmi             -c
OCAMLOPT elpi_ptmap.cmx             -c
OCAMLOPT elpi_data.cmx              -c
OCAMLOPT elpi_compiler.cmi          -c
OCAMLOPT elpi_runtime.cmi           -c
OCAMLOPT elpi_runtime_trace_on.cmx  -c -ppx 'trace_ppx -on' -for-pack
Failure("Ast_mapper: OCaml version mismatch or malformed input")
File "elpi_runtime.ml", line 1:
Error: Error while running external preprocessor
Command line: ./trace_ppx -on '/var/folders/df/kqdm_fnn70lbsz3jhptnq25h0000gn/T/camlppx3e9239' '/var/folders/df/kqdm_fnn70lbsz3jhptnq25h0000gn/T/camlppxa42828'

make: *** [elpi_runtime_trace_on.cmx] Error 2`

Double checked Ocaml version, and have reinstalled ppx packages. On OSX Darwin.

**Comment by gares** [comment]
It may help to know which version you are trying to compile (it does not seem master) and which ocaml version you have.

Best

**Comment by krpcannon** [comment]
Switched down to Ocaml 4.02.3, because that's the check in the makefile. Reinstalled opam packages too.

Also, just pulled from origin. Same error.

Thanks

**Comment by gares** [comment]
please to a `git clean -dfx` and then `make H=` to get verbose output.

thanks for testing!

**Comment by krpcannon** [comment]
Thanks once again. Not sure sure what to look for [here](https://gist.github.com/krpcannon/cb8ff23566a6203ca6fa007b679cadd8).

**Comment by gares** [comment]
Oh nice, elpi did compile after the git clean.
What did not work is the linux only hack to find out where the software is.
Change this line 
  https://github.com/LPCIC/elpi/blob/master/elpi_parser.ml#L38
into
  `let execname = "./elpi" in`
and it should work, but wil work only if you start elpi as in `./elpi`. It will not work if you start
as in `../../whatever/elpi`.

I'm now aware of any decent portable alternative, but at least we can put a try-with around the line and fallback to "./elpi".

**Comment by gares** [comment]
I did push a commit with that change

**Comment by krpcannon** [comment]
Beautiful. Thanks Enrico!
