### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by fblanqui** [LPCIC/elpi#74]
plece -> place
in in -> in
Some other -> Some others
are are -> are

**Comment by fblanqui** [comment]
https://github.com/LPCIC/elpi/blob/f9e31ae8e92d53cf7cbbc5df3f9fd1587c0fd5e0/src/API.mli#L226
thi1 -> this

**Comment by gares** [comment]
many thanks! (as you know, I'm very bad at typos ;-)

**Comment by gares** [comment]
fixed
