### ISSUE TITLE
Type errors with type `o`?

### ISSUE THREAD

**Issue by jfschaefer** [LPCIC/elpi#93]
In the following example
```
kind o type.
type h (list o) -> o -> prop.
h [X|_] X.
```
I get the error
```
line 3: Error: X has type o but is used with type prop
```

I use the most recent opam release (1.12.0).

Using `elpi -print-ast` I noticed that it parses `o` once as `o` and once as `prop`. So `h` has the type
```
ty =
       (Ast.Term.App ((Ast.Term.Const ->),
          [(Ast.Term.App ((Ast.Term.Const list), [(Ast.Term.Const o)]));
            (Ast.Term.App ((Ast.Term.Const ->), [(Ast.Term.Const prop); (Ast.Term.Const prop)]))]
          ))
       });
```
It looks like unintended behaviour to me.

Is `o` intended as a synonym for `prop`?

**Comment by gares** [comment]
> Is `o` intended as a synonym for `prop`?

Yes, and you found a bug in the code replacing `o` with `prop`. I pushed a fix to a branch I'm going to merge and release as 1.13 soon.
