### ISSUE TITLE
Elpi predicate to force garbage collection

### ISSUE THREAD

**Issue by pi8027** [LPCIC/elpi#96]
I wish to have an Elpi predicate to force a garbage collection. There are some OCaml functions (`Gc.minor`, `Gc.major`, `Gc.full_major`, and `Gc.compact`) to do that and `Gc.compact` is most desirable among those for me. @gares

**Comment by gares** [comment]
While we are at it, lets do the whole shopping list.
I guess also `get` `set` and `print_stat` would be good to have.

**Comment by gares** [comment]
please have a look at https://github.com/LPCIC/elpi/pull/97
